import io
from datetime import date, datetime

from fastapi import HTTPException, status
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session, selectinload

from app.models import BookCopy, DamagedBook, Fine, IssueRecord, LostBook, ReceiveRecord, Reservation, Student, User


def clean_optional(value: str | None) -> str | None:
    if value is None:
        return None
    value = value.strip()
    return value or None


def parse_date(value: str | None, fallback: date | None = None) -> date:
    value = clean_optional(value)
    if value:
        return date.fromisoformat(value)
    return fallback or date.today()


def find_student_for_clearance(db: Session, query: str) -> Student | None:
    query = query.strip()
    return db.scalar(
        select(Student).where(
            or_(
                Student.registration_number == query,
                Student.admission_number == query,
                Student.name.ilike(f"%{query}%"),
            )
        )
    )


def student_clearance_context(db: Session, student: Student) -> dict:
    issues = db.scalars(
        select(IssueRecord)
        .options(selectinload(IssueRecord.book_copy), selectinload(IssueRecord.book_master), selectinload(IssueRecord.receive_record), selectinload(IssueRecord.fines))
        .where(IssueRecord.student_id == student.id)
        .order_by(IssueRecord.created_at.desc())
    ).all()
    active_issues = [item for item in issues if item.status == "Active"]
    returns = db.scalars(
        select(ReceiveRecord)
        .join(ReceiveRecord.issue_record)
        .options(selectinload(ReceiveRecord.issue_record), selectinload(ReceiveRecord.book_copy))
        .where(IssueRecord.student_id == student.id)
        .order_by(ReceiveRecord.receive_date.desc())
    ).all()
    overdue_history = [item for item in issues if item.due_date < date.today() and item.status == "Active"]
    unpaid_fines = db.scalars(
        select(Fine)
        .options(selectinload(Fine.book_copy))
        .where(Fine.student_id == student.id, Fine.payment_status.in_(["Unpaid", "Partial"]))
        .order_by(Fine.created_at.desc())
    ).all()
    lost_cases = db.scalars(
        select(LostBook)
        .options(selectinload(LostBook.book_copy))
        .where(LostBook.student_id == student.id, LostBook.resolved_status == "Unresolved")
    ).all()
    damaged_cases = db.scalars(
        select(DamagedBook)
        .options(selectinload(DamagedBook.book_copy))
        .where(DamagedBook.student_id == student.id, DamagedBook.resolved_status == "Unresolved")
    ).all()
    blockers = []
    if active_issues:
        blockers.append("Active issue exists.")
    if unpaid_fines:
        blockers.append("Unpaid fine exists.")
    if lost_cases:
        blockers.append("Unresolved lost book case exists.")
    if damaged_cases:
        blockers.append("Unresolved damaged book case exists.")
    return {
        "issues": issues,
        "active_issues": active_issues,
        "returns": returns,
        "overdue_history": overdue_history,
        "unpaid_fines": unpaid_fines,
        "lost_cases": lost_cases,
        "damaged_cases": damaged_cases,
        "blockers": blockers,
        "eligible": not blockers,
    }


def clear_student(db: Session, student: Student, remarks: str, current_user: User) -> Student:
    context = student_clearance_context(db, student)
    if not context["eligible"]:
        raise ValueError("Student cannot be cleared while blockers exist.")
    remarks = clean_optional(remarks)
    if not remarks:
        raise ValueError("Clearance remarks are required.")
    student.clearance_status = "Cleared"
    student.status = "Cleared"
    student.clearance_date = date.today()
    student.clearance_remarks = remarks
    db.add(student)
    db.commit()
    db.refresh(student)
    return student


def clearance_pdf_bytes(student: Student, context: dict, generated_by: User) -> bytes:
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 60
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Dr A Q Khan Institute of Computer Sciences and Information Technology")
    y -= 22
    pdf.drawString(50, y, "KICSIT Library Student Clearance Letter")
    y -= 35
    pdf.setFont("Helvetica", 10)
    lines = [
        f"Student Name: {student.name}",
        f"Registration Number: {student.registration_number}",
        f"Admission Number: {student.admission_number or ''}",
        f"Department: {student.department or ''}",
        f"Clearance Status: {student.clearance_status}",
        f"Clearance Date: {student.clearance_date or ''}",
        f"Generated By: {generated_by.full_name}",
        f"Generated Date: {date.today().isoformat()}",
        f"Remarks: {student.clearance_remarks or ''}",
    ]
    for line in lines:
        pdf.drawString(50, y, line)
        y -= 18
    y -= 20
    pdf.drawString(50, y, f"Active Issues: {len(context['active_issues'])}")
    y -= 18
    pdf.drawString(50, y, f"Unpaid Fines: {len(context['unpaid_fines'])}")
    y -= 18
    pdf.drawString(50, y, f"Lost Cases: {len(context['lost_cases'])}")
    y -= 18
    pdf.drawString(50, y, f"Damaged Cases: {len(context['damaged_cases'])}")
    y -= 80
    pdf.line(50, y, 220, y)
    pdf.drawString(75, y - 16, "Librarian Signature")
    pdf.line(340, y, 510, y)
    pdf.drawString(370, y - 16, "Office Signature")
    pdf.save()
    buffer.seek(0)
    return buffer.getvalue()


def book_history_by_accession(db: Session, accession_number: str, selected_date: date | None = None) -> dict:
    copy = db.scalar(
        select(BookCopy)
        .options(selectinload(BookCopy.book_master))
        .where(BookCopy.accession_number == accession_number.strip())
    )
    if copy is None:
        raise ValueError("Book copy not found.")
    issues = db.scalars(
        select(IssueRecord)
        .options(selectinload(IssueRecord.student), selectinload(IssueRecord.employee), selectinload(IssueRecord.receive_record))
        .where(IssueRecord.book_copy_id == copy.id)
        .order_by(IssueRecord.issue_date.desc())
    ).all()
    receives = db.scalars(select(ReceiveRecord).where(ReceiveRecord.book_copy_id == copy.id).order_by(ReceiveRecord.receive_date.desc())).all()
    reservations = db.scalars(select(Reservation).where(Reservation.book_copy_id == copy.id).order_by(Reservation.created_at.desc())).all()
    fines = db.scalars(select(Fine).where(Fine.book_copy_id == copy.id).order_by(Fine.created_at.desc())).all()
    lost = db.scalars(select(LostBook).where(LostBook.book_copy_id == copy.id).order_by(LostBook.created_at.desc())).all()
    damaged = db.scalars(select(DamagedBook).where(DamagedBook.book_copy_id == copy.id).order_by(DamagedBook.created_at.desc())).all()
    selected_date = selected_date or date.today()
    in_library = True
    holder = None
    for issue in sorted(issues, key=lambda item: item.issue_date):
        receive = issue.receive_record
        if issue.issue_date <= selected_date and (receive is None or receive.receive_date > selected_date):
            in_library = False
            holder = issue.student.name if issue.student else issue.employee.name
    return {
        "copy": copy,
        "issues": issues,
        "receives": receives,
        "reservations": reservations,
        "fines": fines,
        "lost": lost,
        "damaged": damaged,
        "issued_count": len(issues),
        "returned_count": len(receives),
        "selected_date": selected_date,
        "in_library": in_library,
        "holder": holder,
    }


def consistency_mismatches(db: Session) -> list[dict]:
    mismatches: list[dict] = []
    copies = db.scalars(select(BookCopy).where(BookCopy.is_deleted == False)).all()  # noqa: E712
    for copy in copies:
        active_issue = db.scalar(select(IssueRecord).where(IssueRecord.book_copy_id == copy.id, IssueRecord.status == "Active"))
        active_reservation = db.scalar(select(Reservation).where(Reservation.book_copy_id == copy.id, Reservation.status.in_(["Waiting", "Ready for pickup"])))
        if copy.status == "Available" and active_issue:
            mismatches.append({"copy": copy, "type": "Available with active issue", "expected_status": "Issued", "detail": active_issue.issue_number})
        if copy.status == "Issued" and not active_issue:
            mismatches.append({"copy": copy, "type": "Issued without active issue", "expected_status": "Available", "detail": "No active issue"})
        if copy.status == "Reserved" and not active_reservation:
            mismatches.append({"copy": copy, "type": "Reserved without active reservation", "expected_status": "Available", "detail": "No active reservation"})
    fine_without_receive = db.scalars(select(Fine).where(Fine.receive_record_id == None, Fine.fine_type == "Overdue")).all()  # noqa: E711
    for fine in fine_without_receive:
        if fine.book_copy:
            mismatches.append({"copy": fine.book_copy, "type": "Overdue fine without receive", "expected_status": fine.book_copy.status, "detail": fine.fine_number})
    receives_with_active_issue = db.scalars(
        select(ReceiveRecord)
        .join(ReceiveRecord.issue_record)
        .where(IssueRecord.status == "Active")
    ).all()
    for receive in receives_with_active_issue:
        mismatches.append({"copy": receive.book_copy, "type": "Receive exists but issue active", "expected_status": "Available", "detail": receive.receive_number})
    return mismatches


def correct_copy_status(db: Session, copy_id: int, new_status: str, reason: str, current_user: User) -> BookCopy:
    reason = clean_optional(reason)
    if not reason:
        raise ValueError("Correction reason is required.")
    copy = db.get(BookCopy, copy_id)
    if copy is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Book copy not found")
    copy.status = new_status
    copy.updated_at = datetime.utcnow()
    db.add(copy)
    db.commit()
    db.refresh(copy)
    return copy

